[package]
name = "substrate-bft"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
futures = "0.1.17"
substrate-client = { path = "../client" }
substrate-primitives = { path = "../primitives" }
ed25519 = { path = "../ed25519" }
tokio-timer = "0.1.2"
